apiVersion: v1
kind: ConfigMap
metadata:
 name:  backend
 namespace: expense 
data:
 DB_HOST: mysql


---
kind: Deployment
apiVersion: apps/v1
metadata: 
 name: backend
 namespace: expense
 labels: 
  app: backend
  tier: db
  project: expense
spec: 
  replicas: 2
  selector:
    matchLabels:
     app: backend
     tier: api
     project: expense
  template:
   metadata: 
    labels: 
     app: backend
     tier: api
     project: expense
   spec: 
    containers: 
    - name: backend
      image: madhupitchapati/backend:v1
      envFrom:
      - configMapRef:
           name:  backend
      ports: 
      - containerPort: 80

---

kind: Service
apiVersion: v1
metadata: 
  name: backend
  namespace: expense
spec: 
  selector: 
    app: backend
    tier: api
    project: expense
  ports: 
  - name: backend-port
    protocol: TCP
    port: 8080 #Service Port
    targetPort: 8080 #container Port
